site_name: emodpy-hiv
site_url: https://emod.idmod.org/emodpy-hiv/
repo_name: EMOD-Hub/emodpy-hiv
repo_url: https://github.com/EMOD-Hub/emodpy-hiv/

theme:
  name: material
  custom_dir: docs/customization/overrides
  font: 
    text: Roboto
    code: Roboto Mono
  logo: images/EMOD_logo.png
  favicon: images/favicon.ico
  features:
    - content.code.copy
    # - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: light blue

nav:
  - Home: index.md
  - Installation:
    - Installation: installation.md
    - Virtual environments: virtual_environments.md
  - Tutorials:
    - Overview: tutorials/overview.md
    - Setup: tutorials/setup.md
    - Input concepts: tutorials/concepts.md
    - Tutorial 1 - Run a simulation: tutorials/tutorial-1.md
    - Tutorial 2 - Add reports and plot results: tutorials/tutorial-2.md
    - Tutorial 3 - Customize with build functions: tutorials/tutorial-3.md
    - Tutorial 4 - Override the cascade of care: tutorials/tutorial-4.md
  - Software:
    - Overview: emod/software-overview.md
    - Inputs:
        - Overview: emod/software-inputs.md
        - Demographics: emod/software-demographics.md
        - Demographics overlay files: emod/software-demographics-overlay.md
        - Configuration: emod/software-configuration.md
        - Campaign: emod/software-campaign.md
        - Migration:
            - Overview: emod/software-migration.md
            - How to create migration files: emod/software-migration-creation.md
        - Load-balancing files: emod/software-load-balancing.md
    - Output reports:
        - Overview: emod/software-outputs.md
        - Plot simulation output: emod/software-plotting.md
    - Troubleshooting: emod/troubleshooting.md
    - Tips and tricks:
        - emod/software-simulation-performance.md
  - Model:
      - Overview: emod/model-overview.md
      - STI model:
          - Overview: emod/sti-model-overview.md
          - emod/sti-model-relationships.md
          - emod/sti-model-transmission.md
      - HIV model:
          - Overview: emod/hiv-model-overview.md
          - emod/hiv-model-intrahost.md
          - emod/hiv-model-healthcare-systems.md
      - emod/model-outbreak.md
      - Heterogeneity:
          - Overview: emod/model-heterogeneity.md
          - emod/model-population-density.md
          - emod/model-properties.md
          - emod/model-migration.md
      - Campaign:
          - Overview: emod/model-campaign.md
          - emod/model-targeted-interventions.md
          - emod/model-vaccination.md
          - emod/model-care-cascade.md
  - emod/hiv-disease-overview.md
  - Parameters:
      - Overview: emod/parameter-overview.md
      - emod/parameter-demographics.md
      - Configuration:
          - Overview: emod/parameter-configuration.md
          - emod/parameter-configuration-disease-progression.md
          - emod/parameter-configuration-drugs.md
          - emod/parameter-configuration-enable.md
          - emod/parameter-configuration-env.md
          - emod/parameter-configuration-immunity.md
          - emod/parameter-configuration-incubation.md
          - emod/parameter-configuration-infectivity.md
          - emod/parameter-configuration-input.md
          - emod/parameter-configuration-migration.md
          - emod/parameter-configuration-mortality.md
          - emod/parameter-configuration-output.md
          - emod/parameter-configuration-population.md
          - emod/parameter-configuration-pairs.md
          - emod/parameter-configuration-sampling.md
          - emod/parameter-configuration-scalars.md
          - emod/parameter-configuration-setup.md
          - emod/parameter-configuration-symptoms.md
          - emod/parameter-configuration-weibull.md
      - Campaign:
          - Overview: emod/parameter-campaign.md
          - Event coordinators:
              - Overview: emod/parameter-campaign-event-coordinators.md
              - emod/parameter-campaign-event-broadcastcoordinatorevent.md
              - emod/parameter-campaign-event-calendareventcoordinator.md
              - emod/parameter-campaign-event-campaignevent.md
              - emod/parameter-campaign-event-campaigneventbyyear.md
              - emod/parameter-campaign-event-communityhealthworkereventcoordinator.md
              - emod/parameter-campaign-event-coveragebynodeeventcoordinator.md
              - emod/parameter-campaign-event-delayeventcoordinator.md
              - emod/parameter-campaign-event-incidenceeventcoordinator.md
              - emod/parameter-campaign-event-nchoosereventcoordinator.md
              - emod/parameter-campaign-event-nchoosereventcoordinatorhiv.md
              - emod/parameter-campaign-event-nchoosereventcoordinatorsti.md
              - emod/parameter-campaign-event-referencetrackingeventcoordinator.md
              - emod/parameter-campaign-event-referencetrackingeventcoordinatorhiv.md
              - emod/parameter-campaign-event-referencetrackingeventcoordinatortrackingconfig.md
              - emod/parameter-campaign-event-standardinterventiondistributioneventcoordinator.md
              - emod/parameter-campaign-event-surveillanceeventcoordinator.md
              - emod/parameter-campaign-event-triggeredeventcoordinator.md
          - Node IVs:
              - Overview: emod/parameter-campaign-node-interventions.md
              - emod/parameter-campaign-node-birthtriggerediv.md
              - emod/parameter-campaign-node-broadcastcoordinatoreventfromnode.md
              - emod/parameter-campaign-node-broadcastnodeevent.md
              - emod/parameter-campaign-node-coitalactratechanger.md
              - emod/parameter-campaign-node-condomusageprobabilitychanger.md
              - emod/parameter-campaign-node-firstnodewithnodepropertyeventcoordinator.md
              - emod/parameter-campaign-node-importpressure.md
              - emod/parameter-campaign-node-migratefamily.md
              - emod/parameter-campaign-node-multinodeinterventiondistributor.md
              - emod/parameter-campaign-node-nodelevelhealthtriggerediv.md
              - emod/parameter-campaign-node-nodepropertyvaluechanger.md
              - emod/parameter-campaign-node-nlhtivnode.md
              - emod/parameter-campaign-node-outbreak.md
              - emod/parameter-campaign-node-relationshipdurationchanger.md
              - emod/parameter-campaign-node-relationshipformationratechanger.md
          - Individual IVs:
              - Overview: emod/parameter-campaign-individual-interventions.md
              - emod/parameter-campaign-individual-agediagnostic.md
              - emod/parameter-campaign-individual-antiretroviraltherapy.md
              - emod/parameter-campaign-individual-antiretroviraltherapyfull.md
              - emod/parameter-campaign-individual-artdropout.md
              - emod/parameter-campaign-individual-artmortalitytable.md
              - emod/parameter-campaign-individual-broadcastevent.md
              - emod/parameter-campaign-individual-broadcasteventtoothernodes.md
              - emod/parameter-campaign-individual-cd4diagnostic.md
              - emod/parameter-campaign-individual-coitalactriskfactors.md
              - emod/parameter-campaign-individual-controlledvaccine.md
              - emod/parameter-campaign-individual-delayedintervention.md
              - emod/parameter-campaign-individual-femalecontraceptive.md
              - emod/parameter-campaign-individual-hivartstagingbycd4diagnostic.md
              - emod/parameter-campaign-individual-hivartstagingcd4agnosticdiagnostic.md
              - emod/parameter-campaign-individual-hivdelayedintervention.md
              - emod/parameter-campaign-individual-hivdrawblood.md
              - emod/parameter-campaign-individual-hivmuxer.md
              - emod/parameter-campaign-individual-hivpiecewisebyyearandsexdiagnostic.md
              - emod/parameter-campaign-individual-hivrandomchoice.md
              - emod/parameter-campaign-individual-hivrapidhivdiagnostic.md
              - emod/parameter-campaign-individual-hivsigmoidbyyearandsexdiagnostic.md
              - emod/parameter-campaign-individual-hivsimplediagnostic.md
              - emod/parameter-campaign-individual-immunitybloodtest.md
              - emod/parameter-campaign-individual-individualimmunitychanger.md
              - emod/parameter-campaign-individual-individualnondiseasedeathratemodifier.md
              - emod/parameter-campaign-individual-interventionforcurrentpartners.md
              - emod/parameter-campaign-individual-ivcalendar.md
              - emod/parameter-campaign-individual-malecircumcision.md
              - emod/parameter-campaign-individual-migrateindividuals.md
              - emod/parameter-campaign-individual-modifysticoinfectionstatus.md
              - emod/parameter-campaign-individual-multieffectboostervaccine.md
              - emod/parameter-campaign-individual-multieffectvaccine.md
              - emod/parameter-campaign-individual-multiinterventiondistributor.md
              - emod/parameter-campaign-individual-outbreakindividual.md
              - emod/parameter-campaign-individual-pmtct.md
              - emod/parameter-campaign-individual-propertyvaluechanger.md
              - emod/parameter-campaign-individual-simpleboostervaccine.md
              - emod/parameter-campaign-individual-simplediagnostic.md
              - emod/parameter-campaign-individual-simplehealthseekingbehavior.md
              - emod/parameter-campaign-individual-simplevaccine.md
              - emod/parameter-campaign-individual-standarddiagnostic.md
              - emod/parameter-campaign-individual-startnewrelationship.md
              - emod/parameter-campaign-individual-stibarrier.md
              - emod/parameter-campaign-individual-sticoinfectiondiagnostic.md
              - emod/parameter-campaign-individual-stiispostdebut.md
          - emod/parameter-campaign-waningeffects.md
          - emod/parameter-campaign-targeting-config.md
          - emod/parameter-campaign-event-list.md
      - Reports:
          - Overview: emod/parameter-reports-overview.md
          - General reports:
            - emod/software-report-binned.md
            - emod/software-report-demographic-summary.md
            - emod/software-report-inset-chart.md
            - emod/software-report-property.md
            - emod/software-report-event-counter.md
            - emod/software-report-event-recorder.md
            - emod/software-report-human-migration.md
            - emod/software-report-infection-duration.md
            - emod/software-report-node-demographics.md
            - emod/software-report-simulation-stats.md
            - emod/software-report-spatial.md
            - emod/software-report-sql.md
          - HIV reports:
            - emod/software-report-hivmort.md
            - emod/software-report-hivart.md
            - emod/software-report-age-gender.md
            - emod/software-report-hivinfection.md
            - emod/software-report-transmission.md
          - Relationship reports:
            - emod/software-report-relationship-consummated.md
            - emod/software-report-relationship-end.md
            - emod/software-report-relationship-start.md
            - emod/software-report-relationship-census.md
            - emod/software-report-relationship-migration-tracking.md
          - Error and logging files: emod/software-error-logging.md
      - Schema: emod/parameter-schema.md
  - Glossary: glossary.md
  - API reference: autoapi/
  - Related projects: https://emod.idmod.org/

not_in_nav: |
  bib.md

plugins:
  - search:
  - autorefs:
  - include-markdown:
  - glightbox:
  - table-reader:
  - mkdocs-autoapi:
      autoapi_ignore:
        - .github/**/*
        - build/**/*
        - docs/**/*
        - emodpy_hiv/**/__main__.py
        - examples/**/*
        - notebooks/**/*
        - tests/**/*
        - tutorials/**/*
        - env/**/*
        - venv/**/*
      autoapi_add_nav_entry: false
  - mkdocstrings:

markdown_extensions:
  - admonition:
  - attr_list:  # enables HTMl and CSS classes to inline elements
  - def_list:
  - footnotes:
  - md_in_html:  # enables grids
  - pymdownx.arithmatex:  # Latex processing for math equations
      generic: true
  - pymdownx.blocks.caption:  # captions for images, tables, etc.
  - pymdownx.blocks.details:  # allows nesting of collapsible code
  - pymdownx.caret:  # superscripts
  - pymdownx.details:  # collapsible elements
  - pymdownx.emoji:  # emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:  # syntax highlighting for code blocks
      linenums: true  # adds line numbers to code blocks automatically
      anchor_linenums: true  # adds HTML anchors (#L1, #L2, etc.) to each line so you can link to specific ones.
      default_lang: 'python'
  - pymdownx.mark:  # text highlighting
  - pymdownx.snippets:  # snippet reuse functionality
      auto_append:
        - docs/bib.md
  - pymdownx.tabbed:  # content tabs
      alternate_style: true
  - pymdownx.tilde:  # subscripts

copyright: Copyright &copy; 2025 Gates Foundation. All rights reserved.

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - customization/css/extra.css

extra:
  generator: false  # Removes acknowledgement of mkdocs-material
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EMOD-Hub/
    - icon: octicons/comment-discussion-24
      link: https://github.com/EMOD-Hub/issues-and-discussions
    - icon: octicons/globe-24
      link: https://idmod.org
    - icon: simple/youtube
      link: http://www.youtube.com/@institutefordiseasemodelin1987
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/institute-disease-modeling
  analytics:
    provider: custom
    property: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
